/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Adrian
 */
public class Game extends javax.swing.JFrame {

  /**
   * Creates new form Game
   */
  public Game() {
    initComponents();
    
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLayeredPaneAll = new javax.swing.JLayeredPane();
    jLayeredSecondBlue = new javax.swing.JLayeredPane();
    jLabelSecondBlue = new javax.swing.JLabel();
    jLayeredFirstBrown = new javax.swing.JLayeredPane();
    jLabelFirstBrown = new javax.swing.JLabel();
    jLayeredPaneBoard = new javax.swing.JLayeredPane();
    jLabelBoardImg = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jToggleButton1 = new javax.swing.JToggleButton();
    jButton2 = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Snake and Ladders");

    jLabelSecondBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/figure_blue.png"))); // NOI18N

    javax.swing.GroupLayout jLayeredSecondBlueLayout = new javax.swing.GroupLayout(jLayeredSecondBlue);
    jLayeredSecondBlue.setLayout(jLayeredSecondBlueLayout);
    jLayeredSecondBlueLayout.setHorizontalGroup(
      jLayeredSecondBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredSecondBlueLayout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(jLabelSecondBlue)
        .addContainerGap(436, Short.MAX_VALUE))
    );
    jLayeredSecondBlueLayout.setVerticalGroup(
      jLayeredSecondBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredSecondBlueLayout.createSequentialGroup()
        .addContainerGap(321, Short.MAX_VALUE)
        .addComponent(jLabelSecondBlue)
        .addGap(19, 19, 19))
    );
    jLayeredSecondBlue.setLayer(jLabelSecondBlue, javax.swing.JLayeredPane.DEFAULT_LAYER);

    jLabelFirstBrown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/figure_brown.png"))); // NOI18N

    javax.swing.GroupLayout jLayeredFirstBrownLayout = new javax.swing.GroupLayout(jLayeredFirstBrown);
    jLayeredFirstBrown.setLayout(jLayeredFirstBrownLayout);
    jLayeredFirstBrownLayout.setHorizontalGroup(
      jLayeredFirstBrownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredFirstBrownLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabelFirstBrown)
        .addContainerGap(451, Short.MAX_VALUE))
    );
    jLayeredFirstBrownLayout.setVerticalGroup(
      jLayeredFirstBrownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredFirstBrownLayout.createSequentialGroup()
        .addContainerGap(334, Short.MAX_VALUE)
        .addComponent(jLabelFirstBrown)
        .addContainerGap())
    );
    jLayeredFirstBrown.setLayer(jLabelFirstBrown, javax.swing.JLayeredPane.DEFAULT_LAYER);

    jLabelBoardImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SnakeAndLadders1_small.jpg"))); // NOI18N

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Game Situation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel3.setText("Round:");

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel6.setText("Playing Time:");

    jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel7.setText("1:21");

    jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel8.setText("16");

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel4.setText("Turn:");

    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(0, 0, 255));
    jLabel9.setText("Blue");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel6)
          .addComponent(jLabel3)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel9)
          .addComponent(jLabel8)
          .addComponent(jLabel7))
        .addContainerGap(20, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(jLabel7))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jLabel9))
        .addContainerGap(23, Short.MAX_VALUE))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Switch Player", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

    jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jToggleButton1.setText("Computer");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        .addContainerGap())
    );

    jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jButton2.setText("Move");

    jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jButton1.setText("Back");

    javax.swing.GroupLayout jLayeredPaneBoardLayout = new javax.swing.GroupLayout(jLayeredPaneBoard);
    jLayeredPaneBoard.setLayout(jLayeredPaneBoardLayout);
    jLayeredPaneBoardLayout.setHorizontalGroup(
      jLayeredPaneBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPaneBoardLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabelBoardImg)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jLayeredPaneBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
    jLayeredPaneBoardLayout.setVerticalGroup(
      jLayeredPaneBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPaneBoardLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jLayeredPaneBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(jLayeredPaneBoardLayout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabelBoardImg))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jLayeredPaneBoard.setLayer(jLabelBoardImg, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPaneBoard.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPaneBoard.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPaneBoard.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPaneBoard.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPaneAllLayout = new javax.swing.GroupLayout(jLayeredPaneAll);
    jLayeredPaneAll.setLayout(jLayeredPaneAllLayout);
    jLayeredPaneAllLayout.setHorizontalGroup(
      jLayeredPaneAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLayeredPaneAllLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLayeredPaneBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jLayeredPaneAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPaneAllLayout.createSequentialGroup()
          .addGap(28, 28, 28)
          .addComponent(jLayeredSecondBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(25, Short.MAX_VALUE)))
      .addGroup(jLayeredPaneAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPaneAllLayout.createSequentialGroup()
          .addGap(27, 27, 27)
          .addComponent(jLayeredFirstBrown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(19, Short.MAX_VALUE)))
    );
    jLayeredPaneAllLayout.setVerticalGroup(
      jLayeredPaneAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLayeredPaneBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGroup(jLayeredPaneAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPaneAllLayout.createSequentialGroup()
          .addGap(26, 26, 26)
          .addComponent(jLayeredSecondBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(22, Short.MAX_VALUE)))
      .addGroup(jLayeredPaneAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPaneAllLayout.createSequentialGroup()
          .addGap(21, 21, 21)
          .addComponent(jLayeredFirstBrown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(22, Short.MAX_VALUE)))
    );
    jLayeredPaneAll.setLayer(jLayeredSecondBlue, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPaneAll.setLayer(jLayeredFirstBrown, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPaneAll.setLayer(jLayeredPaneBoard, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLayeredPaneAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(18, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLayeredPaneAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Game().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JLabel jLabelBoardImg;
  private javax.swing.JLabel jLabelFirstBrown;
  private javax.swing.JLabel jLabelSecondBlue;
  private javax.swing.JLayeredPane jLayeredFirstBrown;
  private javax.swing.JLayeredPane jLayeredPaneAll;
  private javax.swing.JLayeredPane jLayeredPaneBoard;
  private javax.swing.JLayeredPane jLayeredSecondBlue;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JToggleButton jToggleButton1;
  // End of variables declaration//GEN-END:variables
}
